### ISSUE TITLE
Voorstel voor tekstuele aanpassing

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/yivi-issue-app#3]
Ik hoor nog vaak dat mensen verward zijn als ze met DigiD inloggen bij gemeente Nijmegen, zoveel dat mensen twijfelen aan de veiligheid…
Mensen lezen de tekst helaas niet. Ik denk dat het zo beter gaat, voorstel om het zo te veranderen:
[DigiD logo] Inloggen met DigiD bij gemeente Nijmegen
Direct daaronder de toelichting: Iedereen kan met dank aan de gemeente Nijmegen persoonsgegevens en adres aan IRMA toevoegen.
Rest van de tekst kan dan weg

Uw attributen zijn succesvol geladen”
Zag ik nog open staan na opnieuw binnenhalen via DigiD. Ook punt voor verbetering, term attributen hebben we destijds vervangen door ‘gegevens’

**Comment by marnixdessing** [comment]
Nieuwe frontend is gebouwd.
