### ISSUE TITLE
siteimprove loslaten op de pagina's

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/yivi-issue-app#7]
zie ook de opmerkingen bij de huidige pagina's: https://github.com/GemeenteNijmegen/irma-issue-website/issues/3

**Comment by wvdeeckhout** [comment]
uitstellen tot Yivi aanpassing

**Comment by marnixdessing** [comment]
Nieuwe frontend is gebouwd, issues zouden hier in opgelost moeten zijn.
