### ISSUE TITLE
betere foutlogging

### ISSUE THREAD

**Issue by BramWithaar** [GemeenteNijmegen/yivi-issue-app#8]
in ieder geval in de eigen logs, goed doorzoekbaar, de verschillende foutoorzaken loggen:
- api niet bereikbaar
- api te traag
- persoon niet gevonden

hier ook goede meldingen van retourneren aan de gebruiker (aangeven welk deel niet werkt en wat een gebruiker kan doen, bij te trage BRP api bijvoorbeeld wat meer geduld of later nog eens proberen)

**Comment by marnixdessing** [comment]
Vervangen door #96
